2021-11-01 20:54:57,208 INFO    MainThread:11469 [internal.py:wandb_internal():90] W&B internal server running at pid: 11469, started at: 2021-11-01 20:54:57.208207
2021-11-01 20:54:57,210 DEBUG   HandlerThread:11469 [handler.py:handle_request():130] handle_request: check_version
2021-11-01 20:54:57,211 INFO    WriterThread:11469 [datastore.py:open_for_write():77] open: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/run-3utdxjge.wandb
2021-11-01 20:54:57,213 DEBUG   SenderThread:11469 [sender.py:send():238] send: header
2021-11-01 20:54:57,213 DEBUG   SenderThread:11469 [sender.py:send_request():252] send_request: check_version
2021-11-01 20:54:57,637 DEBUG   SenderThread:11469 [sender.py:send():238] send: run
2021-11-01 20:54:58,068 INFO    SenderThread:11469 [dir_watcher.py:__init__():169] watching files in: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files
2021-11-01 20:54:58,068 INFO    SenderThread:11469 [sender.py:_start_run_threads():828] run started: 3utdxjge with start time 1635771296
2021-11-01 20:54:58,069 DEBUG   SenderThread:11469 [sender.py:send():238] send: summary
2021-11-01 20:54:58,069 INFO    SenderThread:11469 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2021-11-01 20:54:58,070 DEBUG   HandlerThread:11469 [handler.py:handle_request():130] handle_request: run_start
2021-11-01 20:54:58,993 DEBUG   HandlerThread:11469 [meta.py:__init__():40] meta init
2021-11-01 20:54:58,994 DEBUG   HandlerThread:11469 [meta.py:__init__():54] meta init done
2021-11-01 20:54:58,994 DEBUG   HandlerThread:11469 [meta.py:probe():214] probe
2021-11-01 20:54:59,000 DEBUG   HandlerThread:11469 [meta.py:_setup_git():204] setup git
2021-11-01 20:54:59,034 DEBUG   HandlerThread:11469 [meta.py:_setup_git():211] setup git done
2021-11-01 20:54:59,034 DEBUG   HandlerThread:11469 [meta.py:_save_pip():58] save pip
2021-11-01 20:54:59,036 DEBUG   HandlerThread:11469 [meta.py:_save_pip():72] save pip done
2021-11-01 20:54:59,036 DEBUG   HandlerThread:11469 [meta.py:_save_conda():79] save conda
2021-11-01 20:54:59,072 INFO    Thread-8  :11469 [dir_watcher.py:_on_file_created():217] file/dir created: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/wandb-summary.json
2021-11-01 20:54:59,073 INFO    Thread-8  :11469 [dir_watcher.py:_on_file_created():217] file/dir created: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/requirements.txt
2021-11-01 20:54:59,074 INFO    Thread-8  :11469 [dir_watcher.py:_on_file_created():217] file/dir created: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/conda-environment.yaml
2021-11-01 20:55:04,071 INFO    Thread-8  :11469 [dir_watcher.py:_on_file_created():217] file/dir created: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/output.log
2021-11-01 20:55:06,072 INFO    Thread-8  :11469 [dir_watcher.py:_on_file_modified():230] file/dir modified: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/output.log
2021-11-01 20:55:06,801 DEBUG   HandlerThread:11469 [meta.py:_save_conda():89] save conda done
2021-11-01 20:55:06,801 DEBUG   HandlerThread:11469 [meta.py:probe():252] probe done
2021-11-01 20:55:06,819 DEBUG   HandlerThread:11469 [handler.py:handle_request():130] handle_request: stop_status
2021-11-01 20:55:06,820 DEBUG   SenderThread:11469 [sender.py:send_request():252] send_request: stop_status
2021-11-01 20:55:07,073 INFO    Thread-8  :11469 [dir_watcher.py:_on_file_created():217] file/dir created: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/wandb-metadata.json
2021-11-01 20:55:07,172 DEBUG   SenderThread:11469 [sender.py:send():238] send: files
2021-11-01 20:55:07,174 INFO    SenderThread:11469 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2021-11-01 20:55:08,073 INFO    Thread-8  :11469 [dir_watcher.py:_on_file_modified():230] file/dir modified: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/output.log
2021-11-01 20:55:08,232 INFO    Thread-11 :11469 [upload_job.py:push():137] Uploaded file /tmp/tmpd1ecul32wandb/1cydizwi-wandb-metadata.json
2021-11-01 20:55:09,673 WARNING MainThread:11469 [internal.py:wandb_internal():146] Internal process interrupt: 1
2021-11-01 20:55:09,848 WARNING MainThread:11469 [internal.py:wandb_internal():146] Internal process interrupt: 2
2021-11-01 20:55:09,848 ERROR   MainThread:11469 [internal.py:wandb_internal():149] Internal process interrupted.
2021-11-01 20:55:10,011 INFO    SenderThread:11469 [sender.py:finish():1091] shutting down sender
2021-11-01 20:55:10,011 INFO    WriterThread:11469 [datastore.py:close():281] close: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/run-3utdxjge.wandb
2021-11-01 20:55:10,011 INFO    SenderThread:11469 [dir_watcher.py:finish():283] shutting down directory watcher
2021-11-01 20:55:10,013 INFO    HandlerThread:11469 [handler.py:finish():731] shutting down handler
2021-11-01 20:55:10,075 INFO    SenderThread:11469 [dir_watcher.py:finish():313] scan: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files
2021-11-01 20:55:10,075 INFO    SenderThread:11469 [dir_watcher.py:finish():327] scan save: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/conda-environment.yaml conda-environment.yaml
2021-11-01 20:55:10,075 INFO    SenderThread:11469 [dir_watcher.py:finish():327] scan save: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/output.log output.log
2021-11-01 20:55:10,076 INFO    SenderThread:11469 [dir_watcher.py:finish():327] scan save: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/config.yaml config.yaml
2021-11-01 20:55:10,076 INFO    SenderThread:11469 [dir_watcher.py:finish():327] scan save: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/requirements.txt requirements.txt
2021-11-01 20:55:10,076 INFO    SenderThread:11469 [dir_watcher.py:finish():327] scan save: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/wandb-metadata.json wandb-metadata.json
2021-11-01 20:55:10,076 INFO    SenderThread:11469 [dir_watcher.py:finish():327] scan save: /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/wandb-summary.json wandb-summary.json
2021-11-01 20:55:10,077 INFO    SenderThread:11469 [file_pusher.py:finish():177] shutting down file pusher
2021-11-01 20:55:10,077 INFO    SenderThread:11469 [file_pusher.py:join():182] waiting for file pusher
2021-11-01 20:55:10,902 INFO    Thread-13 :11469 [upload_job.py:push():137] Uploaded file /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/config.yaml
2021-11-01 20:55:10,924 INFO    Thread-12 :11469 [upload_job.py:push():137] Uploaded file /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/output.log
2021-11-01 20:55:10,981 INFO    Thread-14 :11469 [upload_job.py:push():137] Uploaded file /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/requirements.txt
2021-11-01 20:55:11,132 INFO    Thread-15 :11469 [upload_job.py:push():137] Uploaded file /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205456-3utdxjge/files/wandb-summary.json
2021-11-01 20:56:10,432 WARNING FileStreamThread:11469 [file_stream.py:request_with_retry():466] requests_with_retry encountered retryable exception: 408 Client Error: Request Timeout for url: https://api.wandb.ai/files/lilu/HRSEPP-hrsepp_IO/3utdxjge/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f6d0d61af60>>, args: ('https://api.wandb.ai/files/lilu/HRSEPP-hrsepp_IO/3utdxjge/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 62, 'content': ['ERROR 2021-11-01T12:55:08.011047 2021-11-01 20:55:07.453510: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)\n', 'ERROR 2021-11-01T12:55:08.011047 2021-11-01 20:55:07.472491: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3699850000 Hz\n', 'ERROR 2021-11-01T12:55:08.011047 Traceback (most recent call last):\n', 'ERROR 2021-11-01T12:55:08.011047   File "train.py", line 96, in <module>\n', "ERROR 2021-11-01T12:55:08.011047     save_path='/hard/lilu/SMAP_L4/model/ed_convlstm')\n", 'ERROR 2021-11-01T12:55:08.011047   File "train.py", line 52, in train\n', 'ERROR 2021-11-01T12:55:08.011047     validation_split=0.2)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/wandb/integration/keras/keras.py", line 150, in new_v2\n', 'ERROR 2021-11-01T12:55:08.011047     return old_v2(*args, **kwargs)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1095, in fit\n', 'ERROR 2021-11-01T12:55:08.011047     tmp_logs = self.train_function(iterator)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__\n', 'ERROR 2021-11-01T12:55:08.011047     result = self._call(*args, **kwds)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call\n', 'ERROR 2021-11-01T12:55:08.011047     self._initialize(args, kwds, add_initializers_to=initializers)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize\n', 'ERROR 2021-11-01T12:55:08.011047     *args, **kwds))\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected\n', 'ERROR 2021-11-01T12:55:08.011047     graph_function, _ = self._maybe_define_function(args, kwargs)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function\n', 'ERROR 2021-11-01T12:55:08.011047     graph_function = self._create_graph_function(args, kwargs)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function\n', 'ERROR 2021-11-01T12:55:08.011047     capture_by_value=self._capture_by_value),\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func\n', 'ERROR 2021-11-01T12:55:08.011047     func_outputs = python_func(*func_args, **func_kwargs)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn\n', 'ERROR 2021-11-01T12:55:08.011047     out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n', 'ERROR 2021-11-01T12:55:08.011047   File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper\n', 'ERROR 2021-11-01T12:55:08.011047     raise e.ag_error_metadata.to_exception(e)\n', 'ERROR 2021-11-01T12:55:08.011047 ValueError: in user code:\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:800 train_function  *\n', 'ERROR 2021-11-01T12:55:08.011047         return step_function(self, iterator)\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:790 step_function  **\n', 'ERROR 2021-11-01T12:55:08.011047         outputs = model.distribute_strategy.run(run_step, args=(data,))\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run\n', 'ERROR 2021-11-01T12:55:08.011047         return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica\n', 'ERROR 2021-11-01T12:55:08.011047         return self._call_for_each_replica(fn, args, kwargs)\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica\n', 'ERROR 2021-11-01T12:55:08.011047         return fn(*args, **kwargs)\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:783 run_step  **\n', 'ERROR 2021-11-01T12:55:08.011047         outputs = model.train_step(data)\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:749 train_step\n', 'ERROR 2021-11-01T12:55:08.011047         y_pred = self(x, training=True)\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__\n', 'ERROR 2021-11-01T12:55:08.011047         input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n', 'ERROR 2021-11-01T12:55:08.011047     /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:274 assert_input_compatibility\n', "ERROR 2021-11-01T12:55:08.011047         ', found shape=' + display_shape(x.shape))\n", 'ERROR 2021-11-01T12:55:08.011047     ValueError: Input 0 is incompatible with layer model: expected shape=(None, 1, 224, 224, 8), found shape=(None, 1, 7, 224, 224)\n', '2021-11-01T12:55:08.011155 Epoch 1/50\n']}}, 'dropped': 0}}
2021-11-01 20:56:13,353 INFO    MainThread:11469 [internal.py:handle_exit():77] Internal process exited
